# Generated by Django 6.0 on 2025-12-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField(help_text='Discount in cents')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.FloatField(help_text='Tax percent, e.g. 5.5')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='store.item'),
        ),
        migrations.AddField(
            model_name='order',
            name='discounts',
            field=models.ManyToManyField(blank=True, to='store.discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='taxes',
            field=models.ManyToManyField(blank=True, to='store.tax'),
        ),
    ]
