# Generated by Django 6.0 on 2025-12-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_discount_tax_alter_order_items_order_discounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(default='usd', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(help_text='Price in cents, e.g. 1000 = $10.00', verbose_name='Price (cents)'),
        ),
    ]
